/**
 * @file cmd_setup.cpp
 * @brief Implementation of the "setup" command — interactive configuration wizard.
 */

#include "cmd_setup.h"

#include "../shared/file_utils.h"
#include "../shared/logger.h"

#include <iostream>
#include <string>
#include <vector>

namespace echosmart {

// -----------------------------------------------------------------------
// Prompt helper
// -----------------------------------------------------------------------

/// Print a prompt and read a line.  Returns @p default_val if the user
/// enters an empty string.
static std::string prompt(const std::string& label,
                          const std::string& default_val) {
    std::cout << label;
    if (!default_val.empty()) {
        std::cout << " [" << default_val << "]";
    }
    std::cout << ": ";

    std::string line;
    if (!std::getline(std::cin, line)) return default_val;

    line = trim(line);
    return line.empty() ? default_val : line;
}

// -----------------------------------------------------------------------
// Config file writer
// -----------------------------------------------------------------------

static std::string build_env_content(
        const std::string& gateway_id,
        const std::string& gateway_name,
        const std::string& cloud_api_url,
        const std::string& api_key,
        const std::string& mqtt_broker,
        const std::string& polling_interval) {
    std::string content;
    content += "# EchoSmart Gateway Configuration\n";
    content += "# Generated by echosmart setup\n\n";
    content += "GATEWAY_ID="        + gateway_id      + "\n";
    content += "GATEWAY_NAME="      + gateway_name     + "\n";
    content += "CLOUD_API_URL="     + cloud_api_url    + "\n";
    content += "CLOUD_API_KEY="     + api_key           + "\n";
    content += "MQTT_BROKER="       + mqtt_broker       + "\n";
    content += "POLLING_INTERVAL="  + polling_interval  + "\n";
    content += "SIMULATION_MODE=true\n";
    content += "LOG_LEVEL=INFO\n";
    return content;
}

// -----------------------------------------------------------------------
// Command entry point
// -----------------------------------------------------------------------

int cmd_setup(const CliArgs& args) {
    std::string config_path = args.get("config", "/etc/echosmart/gateway.env");

    std::cout << "=== EchoSmart Gateway Setup ===\n\n";

    std::string gateway_id      = prompt("Gateway ID",        "gw-001");
    std::string gateway_name    = prompt("Gateway Name",      "EchoSmart Gateway");
    std::string cloud_api_url   = prompt("Cloud API URL",     "http://localhost:8000");
    std::string api_key         = prompt("API Key",           "");
    std::string mqtt_broker     = prompt("MQTT Broker",       "localhost");
    std::string polling_interval = prompt("Polling Interval (s)", "60");

    std::string content = build_env_content(
        gateway_id, gateway_name, cloud_api_url,
        api_key, mqtt_broker, polling_interval);

    bool written = write_file(config_path, content);

    std::cout << "\n=== Configuration Summary ===\n"
              << "Gateway ID       : " << gateway_id << "\n"
              << "Gateway Name     : " << gateway_name << "\n"
              << "Cloud API URL    : " << cloud_api_url << "\n"
              << "API Key          : " << (api_key.empty() ? "(not set)" : "***") << "\n"
              << "MQTT Broker      : " << mqtt_broker << "\n"
              << "Polling Interval : " << polling_interval << "s\n";

    if (written) {
        std::cout << "\nConfiguration written to: " << config_path << "\n";
    } else {
        std::cerr << "\nWarning: could not write to " << config_path << "\n"
                  << "You may need to run with sudo or choose a writable path:\n"
                  << "  echosmart setup --config=./gateway.env\n";
    }

    return 0;
}

} // namespace echosmart
